CREATE TYPE ESTADO_GENERAL AS ENUM('ALTA', 'BAJA');

CREATE TYPE ESTADO_MATERIAL AS ENUM('ALTA', 'BAJA', 'ROTO', 'REPARACION');

CREATE TABLE USUARIOS (
	ID_USUARIO SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	ESTADO ESTADO_GENERAL DEFAULT 'ALTA',
	FECHA_ALTA DATE DEFAULT CURRENT_DATE
);

CREATE TABLE OFICINAS (
	ID_OFICINA SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	ESTADO ESTADO_GENERAL DEFAULT 'ALTA',
	FECHA_ALTA DATE DEFAULT CURRENT_DATE
);

CREATE TABLE MATERIALES (
	ID_MATERIAL SERIAL PRIMARY KEY,
	TIPO VARCHAR(50) NOT NULL,
	MARCA VARCHAR(50) NOT NULL,
	MODELO VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(200),
	ESTADO ESTADO_MATERIAL DEFAULT 'ALTA',
	FECHA_ALTA DATE DEFAULT CURRENT_DATE,
	ID_OFICINA INT,
	CONSTRAINT FK_MAT_OFICINA FOREIGN KEY (ID_OFICINA) REFERENCES OFICINAS (ID_OFICINA)
);

CREATE TABLE HISTORIAL_MATERIALES (
	ID_HISTORIAL SERIAL PRIMARY KEY,
	FECHA DATE DEFAULT CURRENT_DATE,
	ID_MATERIAL INT NOT NULL,
	ID_OFICINA INT NOT NULL,
	ID_USUARIO INT NOT NULL,
	ESTADO ESTADO_MATERIAL DEFAULT 'ALTA',
	OBSERVACION VARCHAR(200),
	CONSTRAINT FK_HIST_MAT FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIALES (ID_MATERIAL),
	CONSTRAINT FK_HIST_OFI FOREIGN KEY (ID_OFICINA) REFERENCES OFICINAS (ID_OFICINA),
	CONSTRAINT FK_HIST_USU FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
);

CREATE VIEW VISTA_HISTORIAL AS
SELECT
	H.ID_HISTORIAL AS ID,
	H.FECHA,
	H.ESTADO,
	M.TIPO,
	M.MARCA,
	M.MODELO,
	O.NOMBRE AS OFICINA,
	U.NOMBRE AS USUARIO,
	H.OBSERVACION
	FROM HISTORIAL_MATERIALES H
	JOIN MATERIALES M ON H.ID_MATERIAL = M.ID_MATERIAL
	JOIN OFICINAS O ON H.ID_OFICINA = O.ID_OFICINA
	JOIN USUARIOS U ON H.ID_USUARIO = U.ID_USUARIO;